# URL: https://github.com/jesseduffield/lazygit
gui:
  nerdFontsVersion: "3"
  showDivergenceFromBaseBranch: arrowAndNumber
  switchTabsWithPanelJumpKeys: true
  filterMode: fuzzy
  expandFocusedSidePanel: true
  showRandomTip: false

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --features side-by-side --syntax-theme gruvbox-dark --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"  
  disableForcePushing: false
  overrideGpg: false
