#  ____ _____  _    ____  ____  _   _ ___ ____  
# / ___|_   _|/ \  |  _ \/ ___|| | | |_ _|  _ \ 
# \___ \ | | / _ \ | |_) \___ \| |_| || || |_) |
#  ___) || |/ ___ \|  _ < ___) |  _  || ||  __/ 
# |____/ |_/_/   \_\_| \_\____/|_| |_|___|_|    
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 1000
scan_timeout = 10

format = """
[](color_orange)\
$os\
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[ ](color_aqua)\
$line_break$status$character"""

right_format = """
[](color_aqua)\
[](fg:color_aqua bg:color_blue)\
$c\
$dart\
$rust\
$golang\
$nodejs\
$java\
$kotlin\
$python\
[](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[status]
# style = 'bg:color_red'
symbol = '☠  '
success_symbol = '✅ '
format = '[$symbol$status]($style) '
map_symbol = false
disabled = false

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[$read_only $path ]($style)"
truncation_length = 10 
truncation_symbol = "…/"
truncate_to_repo = true
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[cmake]
format = '[$symbol($version )]($style)'
style = "bg:color_blue"

[dart]
format = '[$symbol($version )]($style)'
style = "bg:color_blue"

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[→](bold fg:color_green)'
error_symbol = '[→](bold fg:color_red)'
vimcmd_symbol = '[←](bold fg:color_green)'
vimcmd_replace_one_symbol = '[←](bold fg:color_purple)'
vimcmd_replace_symbol = '[←](bold fg:color_purple)'
vimcmd_visual_symbol = '[←](bold fg:color_yellow)'
insert_symbol = '[I](bold fg:color_blue)'
normal_symbol = '[N](bold fg:color_red)'
