#  ____ _____  _    ____  ____  _   _ ___ ____  
# / ___|_   _|/ \  |  _ \/ ___|| | | |_ _|  _ \ 
# \___ \ | | / _ \ | |_) \___ \| |_| || || |_) |
#  ___) || |/ ___ \|  _ < ___) |  _  || ||  __/ 
# |____/ |_/_/   \_\_| \_\____/|_| |_|___|_|    
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 2000
scan_timeout = 50

format = """
[](color_orange)\
$os\
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[ ](color_aqua)\
$line_break$status$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[status]
# style = 'bg:color_red'
symbol = '☠  '
success_symbol = '✅ '
format = '[$symbol$status]($style) '
map_symbol = false
disabled = false

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Macos = "󰀵"
Linux = "󰌽"
Android = ""
Arch = "󰣇"
EndeavourOS = ""
Debian = "󰣚"
Pop = ""

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[$read_only $path ]($style)"
truncation_length = 10 
truncation_symbol = "…/"
truncate_to_repo = false
read_only = " 󰌾"

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
# error_symbol = "[󰩈](bold fg:color_red)"
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
# insert_symbol = '[I](bold fg:color_blue)'
# normal_symbol = '[N](bold fg:color_red)'
