Hover:
  ShowAKA: true
Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    Add: [modernize*, bugprone-*, cppcoreguidelines-*]
    Remove: [
              modernize-use-trailing-return-type, 
              modernize-use-nodiscard, 
              modernize-use-override, 
              cppcoreguidelines-explicit-virtual-functions,
              bugprone-easily-swappable-parameters
    ]

InlayHints:
  BlockEnd: true

